# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-04 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='patient_info',
            new_name='client_info',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='patient_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='doctor',
            new_name='master',
        ),
    ]
