# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_human_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUsl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость услуги')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Master', verbose_name='Услуги')),
            ],
        ),
    ]
