# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_masterusl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterusl',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
