# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reception_uslugi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='cost',
            field=models.CharField(default=1, max_length=100, verbose_name='Стоимость услуг'),
            preserve_default=False,
        ),
    ]
