# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200505_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='uslugi',
        ),
        migrations.AlterField(
            model_name='reception',
            name='uslugi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MasterUsl', verbose_name='Услуги '),
        ),
    ]
