# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200505_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterusl',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Master', verbose_name='Услуги'),
            preserve_default=False,
        ),
    ]
