# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_masterusl_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='uslugi',
        ),
    ]
