# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200505_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/users/'),
        ),
        migrations.AddField(
            model_name='reception',
            name='uslugi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.MasterUsl', verbose_name='Услуги '),
            preserve_default=False,
        ),
    ]
