# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_reception_id_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='id_person',
            new_name='person_id',
        ),
    ]
