# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-05 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200505_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='person_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
