# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200505_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль ', 'verbose_name_plural': 'Профили '},
        ),
        migrations.AddField(
            model_name='reception',
            name='cost',
            field=models.CharField(default=1, max_length=100, verbose_name='Стоимость услуг'),
            preserve_default=False,
        ),
    ]
