# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-10 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contactsform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsform',
            name='mail',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
