# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200510_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStock', models.CharField(max_length=200, verbose_name='Название акции')),
                ('price', models.CharField(max_length=200, verbose_name='Стоимость')),
                ('info', models.CharField(max_length=500, verbose_name='Описание акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
