# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=222, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=200, verbose_name='Email')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Stock', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
    ]
