# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-10 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_stockreserv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockreserv',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акционные записи'},
        ),
    ]
