# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200510_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreserv',
            name='person',
            field=models.CharField(max_length=221, verbose_name='ФИО'),
        ),
    ]
