# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-10 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200510_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreserv',
            old_name='person',
            new_name='persons',
        ),
    ]
